### ISSUE TITLE
images not resized on localhost

### ISSUE THREAD

**Issue by enricocaputo** [valerijaspasojevic/jekyll-compress-images#2]
it's weird: first time when I installed plugin Jekyll took some time to build site while shell was writing me this image is optimized other image is optimized and so on.
When I stopped server (ctrl C) and run again (Bundle exec jekyll serve) the build process was faster and nothing about optimization images appears on the shell.

In my _site/images folder (on local) the images has the same original size. But if I retrieve images from my site, published on github pages, the images seem to be smaller. I told it seems because Google Page Speed Insight tell me that the images are not optimized and have the same previous size.

**Comment by reustle** [comment]
I'm having the same issue, no luck debugging it. Read through the source here, not too much info. Did you have any luck?

**Comment by valerijaspasojevic** [comment]
Hi, already optimized images are not going thru optimization, because of that it was fast the second time. When you build your pages in the _site it should appear optimized images. Let me know is this is solving the problem.
