### ISSUE TITLE
Don't overwrite the original image file

### ISSUE THREAD

**Issue by sffc** [valerijaspasojevic/jekyll-compress-images#3]
I'd prefer if the image optimization would dump the optimized images into `_site` without touching the original images.  For example, I want to store high-quality images in the repo and then compress them only when serving.

**Comment by sffc** [comment]
FYI, I created a Gist with a plugin that runs `image_optim` but does not overwrite the original file:

https://gist.github.com/sffc/a828267913591159ab1cc3e1bfde20d7

**Comment by valerijaspasojevic** [comment]
Hi, I will add posibility that you can define in config file would you like to overwrite them or not.
