### ISSUE TITLE
svgo worker not found

### ISSUE THREAD

**Issue by johnpitchko** [valerijaspasojevic/jekyll-compress-images#4]
Received the following error when launching jekyll using the plugin:
```
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
```

In my _config.yml:
```
# Plugins
plugins:
  - jekyll-compress-images

imageoptim:
  # Disabling svgo because it throws some error
  svgo: false
  jpegrecompress:
    allow_lossy: true
    quality: 2
    # max_quality: 80
```

Not sure why svgo worker is being triggered when its specifically disabled in the config.

**Comment by simpixelated** [comment]
It looks like the ability to configure imageoptim was added to `master` but never published:
https://github.com/valerijaspasojevic/jekyll-compress-images/compare/1.2...master

@valerijaspasojevic would you mind publishing a new version with your latest changes?

**Comment by andreadellacorte** [comment]
@valerijaspasojevic please ☝️

**Comment by davidpfahler** [comment]
FYI, you can add the gem to your `Gemfile` like this and it works:

```
gem 'jekyll-compress-images', :git => 'https://github.com/valerijaspasojevic/jekyll-compress-images.git'
```

**Comment by naufdotal** [comment]
you should install svgo worker first with npm.
[svgo installation](https://github.com/toy/image_optim#svgo-installation-optional).

After that, try jekyll build again

**Comment by mikebuss** [comment]
I'm also getting this error. None of the steps above have worked. Editing a file with `--watch` enabled will trigger an infinite loop of the following error message:

```bash
      Regenerating: 1 file(s) changed at 2019-12-26 19:16:25
                    _compress_images_cache.yml
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
       Jekyll Feed: Generating feed for posts
                    ...done in 0.342562 seconds.

      Regenerating: 1 file(s) changed at 2019-12-26 19:16:25
                    _compress_images_cache.yml
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
       Jekyll Feed: Generating feed for posts
                    ...done in 0.357929 seconds.

      Regenerating: 1 file(s) changed at 2019-12-26 19:16:26
                    _compress_images_cache.yml
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
       Jekyll Feed: Generating feed for posts
                    ...done in 0.350581 seconds.

      Regenerating: 1 file(s) changed at 2019-12-26 19:16:26
                    _compress_images_cache.yml
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
       Jekyll Feed: Generating feed for posts
```

Any idea how to fix this? I have tried:

- Installing svgo with `nom install svgo`. No change.
- Using the Gemfile entry that @davidpfahler suggested. No change.
- Adding the following to my _config.yml file:

```yaml
imageoptim:
  pngout: false
  svgo: false
  verbose: false
```

**Comment by samlawski** [comment]
@mikebuss It worked for me to do both together: 

Update the Gemfile as davidpfahler suggested:

```
gem 'jekyll-compress-images', :git => 'https://github.com/valerijaspasojevic/jekyll-compress-images.git'
```

And also add to the _config.yml: 

```
imageoptim:
  svgo: false
```

**Comment by mikebuss** [comment]
Thanks @samlawski. I tried again with what you suggested and it worked, but only after I also added the following line to my configuration file:

```
exclude:
  - _compress_images_cache.yml
```

The 2 changes you suggested and the one above fixed the SVGO error and stopped the infinite regenerating. Thanks for the suggestion!

**Comment by Seva98** [comment]
Cheers @mikebuss, I've had exactly the same issue with infinite loop, your solution worked perfectly!
